name: Deploy partner-product-orch

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set Up node version
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
